language: ruby
dist: trusty
sudo: true
cache: bundler
jdk:
  - openjdk7
rvm:
  - 2.4

script:
  - bundle exec jekyll build
  - bundle exec ./_utils/deploy.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
