language: ruby
dist: trusty
sudo: true

script:
- bundle exec jekyll build
- tar czf website.tar.gz -C _site/ .

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_BUCKET
    local_dir: ./_site
    skip_cleanup: true
    on:
      branch: master
      condition: (-n "${AWS_ACCESS_KEY_ID}") && (-n "${AWS_SECRET_ACCESS_KEY}") && (-n "${AWS_BUCKET}")

after_deploy:
  - pip install awscli
  - ./_utils/invalidate-cloudfront-cache.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
